[project]
name = "wundernn"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11.14"
dependencies = [
    "lightgbm>=4.6.0",
    "scikit-learn>=1.8.0",
    "tqdm>=4.67.1",
]
